# Generated by Django 3.1.7 on 2021-03-17 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'account_status_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100, null=True)),
                ('profile_image', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_master', models.BooleanField(default=False)),
                ('account_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.accountstatus')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
