# Generated by Django 3.1.7 on 2021-03-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MNFCTCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnfct_company', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'MNFCT_company',
            },
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'model_category_TYPE',
            },
        ),
        migrations.CreateModel(
            name='ModelInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name_ko', models.CharField(max_length=30, null=True)),
                ('model_name_en', models.CharField(max_length=30)),
                ('purchase_paid', models.IntegerField(default=0, null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('purchase_location', models.CharField(max_length=30, null=True)),
                ('grnt_period', models.DateField(null=True)),
                ('serial_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('model_categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnt.modelcategory')),
            ],
            options={
                'db_table': 'model_information',
            },
        ),
        migrations.CreateModel(
            name='SVCInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svc_name', models.CharField(max_length=30)),
                ('svc_contact', models.CharField(max_length=30)),
                ('svc_address', models.CharField(max_length=100)),
                ('svc_image', models.CharField(max_length=200, null=True)),
                ('mnfct_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnt.mnfctcompany')),
            ],
            options={
                'db_table': 'svc_information',
            },
        ),
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.URLField()),
                ('model_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnt.modelinformation')),
            ],
            options={
                'db_table': 'receipt_image',
            },
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_group', models.CharField(max_length=30)),
                ('mnfct_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnt.mnfctcompany')),
            ],
            options={
                'db_table': 'model_group_TYPE',
            },
        ),
        migrations.AddField(
            model_name='modelcategory',
            name='model_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnt.modelgroup'),
        ),
        migrations.CreateModel(
            name='GRNTImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grnt_image', models.URLField()),
                ('model_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnt.modelinformation')),
            ],
            options={
                'db_table': 'grnt_image',
            },
        ),
    ]
