# Generated by Django 3.1.7 on 2021-03-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelinformation',
            old_name='account_id',
            new_name='account',
        ),
    ]
