# Generated by Django 3.1.7 on 2021-03-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnt', '0002_auto_20210317_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelinformation',
            old_name='model_categoty',
            new_name='model_category',
        ),
    ]
