# Generated by Django 3.1.7 on 2021-03-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnt', '0003_auto_20210317_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelinformation',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
