# Generated by Django 3.1.7 on 2021-03-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnt', '0004_auto_20210317_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinformation',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
